### ISSUE TITLE
Critical dependencies warning

### ISSUE THREAD

**Issue by stavros-liaskos** [yuheiy/shuffle-letters#2]
I am using [create-react-app](https://github.com/facebookincubator/create-react-app) and shuffle-letters. In create-react-app, webpack configuration is NOT configurable. There is a sensitive warning handler in that project which generates the following error:
``` 
/~/shuffle-letters/dist/shuffle-letters.js
Critical dependencies:
1:487-494 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/shuffle-letters/dist/shuffle-letters.js 1:487-494
```
When importing straight from the source, the warning message remains the same!

1. There is no problem with the functionality so it's not a bug.
2. I am not familiar with building npm libraries but [this post states](https://github.com/webpack/webpack/issues/4263)  that it might be a false positive warning. Maybe [this post](https://github.com/webpack/webpack/issues/1617#issuecomment-181713671) helps too

**Comment by yuheiy** [comment]
I'm sorry, I have lost my motivation for this project. There is [a similar project](https://github.com/ics-ikeda/shuffle-text) so please try it.
